### PR TITLE
Change default deletion shortcut to D

### PR DESCRIPTION
**Pull request by Hummer12007**
react-hotkey breaks when using Delete

### CODE REVIEW

**Comment by seveibar** [comment]
Makes sense to me!

**Comment by Ownmarc** [comment]
Isn't this a lazy fix ? I think we should try to find what the bug is with the delete key and go to a solution like this if there is no way to reliably support the delete key ?

**Comment by Hummer12007** [comment]
I think it is an upstream react-hotkeys issue. I didn't manage to figure it out within an hour though.
react-hotkeys has a fair share of issues on its own (and it's not realy maintained), so it would probably be wiser to migrate to something else in the long run.

**Pull request merged**
